name: Brain Games Checks
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          # force poetry install venv within project dir
          poetry config virtualenvs.in-project true
          make install
      - name: Run linters
        run: |
          make lint


